<?php if (empty($model)) {
    $model = array(
        'assessment_start_date' => 'Demo Client Organization',
        'assessment_end_date' => 'Fall, 2013',
        'num_schools' => 'Demo Client Logo',
        'num_teachers' => '8',
        'num_classrooms' => '4',
        'avg_age' => 'Demo Client Logo',
        'avg_age_boys' => '5',
        'avg_age_girls' => '6',
        'num_children' => '1',
        'data_num_boys_girls' => '32,64',
    );
} ?>
<div>
    <p>The <em>Early Years Evaluation - Teacher Assessment (<strong>EYE-TA</strong>)</em>
        provides a systematic framework teachers can use to structure their frequent observations
        and informal assessments in play-based learning environments<sup>1</sup>. It assesses children's development
        in five domains, which are consistent with frameworks set out by UNICEF and the US Congress<sup>2</sup>:
        <em>Awareness of Self and Environment, Social Skills and Approaches to Learning, Cognitive Skills,
            Language and Communication, and Physical Development</em>.
        The research has shown that the skills in these domains are related to children's literacy development
        and their success at school<sup>3,4</sup>.</p>

    <p>The <em><strong>EYE-TA</strong></em> is a web-based assessment that can be completed by kindergarten
        or grade 1 teachers as part of their regular classroom practice.</p>
</div>
<div>
    <div>Demographic Profile</div>
    <dl>
        <dt>Assessment Period:</dt>
        <dd><?= $model['assessment_start_date'] ?> - <?= $model['assessment_end_date'] ?></dd>
        <dt>Number of participating schools:</dt>
        <dd><?= $model['num_schools'] ?></dd>
        <dt>Number of participating teachers:</dt>
        <dd><?= $model['num_teachers'] ?></dd>
        <dt>Number of participating classrooms:</dt>
        <dd><?= $model['num_classrooms'] ?></dd>
        <dt>Average age on :</dt>
        <dd><?= $model['avg_age'] ?></dd>
        <dl>
            <dt>Boys:</dt>
            <dd><?= $model['avg_age_boys'] ?></dd>
            <dt>Girls:</dt>
            <dd><?= $model['avg_age_girls'] ?></dd>
        </dl>
    </dl>
</div>
<div>
    <dl>
        <dt>Number of children assessed:</dt>
        <dd><?= $model['num_children'] ?></dd>
    </dl>
    <p>Breakdown of boys and girls:</p>

    <div id="numOfBoysAndGirls"></div>
</div>
<div>
    <p>Boys - Age on </p>
    <canvas id="agesOfBoys"></canvas>
    <p>Girls - Age on </p>
    <canvas id="agesOfGirls"></canvas>
</div>
<div>
    <div>
        <h3>Skill Development</h3>

        <p>The EYE-TA evaluates aspects of early child development in five developmental domains:</p>

        <p><strong>Awareness of Self and Environment</strong> - a child's understanding of the world and his or her
            ability to make connections with home and community experiences;</p>

        <p><strong>Social Skills and Approaches to Learning</strong> - a child's attentiveness during classroom
            activities and his or her ability to interact with peers while respecting classroom rules;</p>

        <p><strong>Cognitive Skills</strong> - a child's basic mathematics and pre-readng skills and his or her ability
            to solve problems;</p>

        <p><strong>Language and Communication</strong> - a child's understanding of spoken language and his or her
            ability to express thoughts and feelings;</p>

        <p><strong>Physical Development</strong>
            <br/><strong>Fine motor</strong> - a child's ability to perform small movements that require hand-eye
            coordination;
            <br/><strong>Gross motor</strong> - a child's ability to perform large movements that involve arms, legs,
            and body.
        </p>
    </div>
</div>
<script>
    $(document).ready(function () {
        c3.generate({
            bindto: '#numOfBoysAndGirls',
            data: {
                columns: [
                    ['data', <?= $model['data_num_boys_girls'] ?>]
                ],
                types: {
                    data: 'bar'
                }
            },
            axis: {
                rotated: true,
                x: {
                    type: 'category',
                    categories: ['Boys', 'Girls']
                }
            }
        });
    });
</script>
